# Generated by Django 5.2 on 2025-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0002_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
