# Generated by Django 5.2 on 2025-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
